version: "2"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data/db:/data/db
  backend:
    build: ./
    container_name: backend
    depends_on:
      - mongo
    environment:
      DEBUG: homusic:*
      PORT: 4000
    links:
      - mongo
    ports:
      - 4000:4000
    command: "npm run serve"
    restart: always
    volumes:
      - ./config:/app/config
      - ./dist:/app/dist
      - ./src:/app/src
      - ./data/artists:/app/data/artists
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
