export type Language = { [letter: string]: string };

const letters: { [language: string]: Language } = {
    en: {
        "a": "a",
        "b": "b",
        "c": "c",
        "d": "d",
        "e": "e",
        "f": "f",
        "g": "g",
        "h": "h",
        "i": "i",
        "j": "j",
        "k": "k",
        "l": "l",
        "m": "m",
        "n": "n",
        "o": "o",
        "p": "p",
        "q": "q",
        "r": "r",
        "s": "s",
        "t": "t",
        "u": "u",
        "v": "v",
        "w": "w",
        "x": "x",
        "y": "y",
        "z": "z"
    },
    ru: {
        "a": "а",
        "b": "б",
        "v": "в",
        "g": "г",
        "d": "д",
        "ye": "е",
        "zh": "ж",
        "z": "з",
        "i": "и",
        "j": "й",
        "k": "к",
        "l": "л",
        "m": "м",
        "n": "н",
        "o": "о",
        "p": "п",
        "r": "р",
        "s": "с",
        "t": "т",
        "u": "у",
        "f": "ф",
        "h": "х",
        "c": "ц",
        "ch": "ч",
        "sh": "ш",
        "sch": "щ",
        "y": "ы",
        "e": "э",
        "yu": "ю",
        "ya": "я"
    }
}

export default letters;
